import * as fs from 'fs';
import * as path from 'path';

describe('Error Message Extraction', () => {
  it('should extract all error messages and update api-docs/error-notes.md', () => {
    const srcDir = path.join(__dirname, '../../src');
    const outputFile = path.join(__dirname, '../../api-docs/error-notes.md');
    const errorMessages: Set<string> = new Set();

    function scanDir(dir: string) {
      const files = fs.readdirSync(dir);
      for (const file of files) {
        const fullPath = path.join(dir, file);
        const stat = fs.statSync(fullPath);
        if (stat.isDirectory()) {
          scanDir(fullPath);
        } else if (file.endsWith('.ts')) {
          const content = fs.readFileSync(fullPath, 'utf-8');
          // Regex to catch new HttpException('message', ...) or new BadRequestException('message')
          // Matches: new SomeException('message' or "message"
          const regex = /new\s+(\w+Exception)\s*\(\s*['"`](.*?)['"`]/g;
          let match;
          while ((match = regex.exec(content)) !== null) {
            const exceptionType = match[1];
            const message = match[2];
            errorMessages.add(`- **${exceptionType}**: "${message}"`);
          }
        }
      }
    }

    scanDir(srcDir);

    const sortedMessages = Array.from(errorMessages).sort();

    // Read existing file
    let existingContent = fs.readFileSync(outputFile, 'utf-8');

    // Define marker
    const marker = '## **6. Auto-Generated Error List**';
    const splitContent = existingContent.split(marker);

    const newContent = `${splitContent[0].trim()}\n\n${marker}\n\nThis list is auto-generated by running the error extraction test.\n\n${sortedMessages.join('\n')}\n`;

    fs.writeFileSync(outputFile, newContent);
    console.log(`Extracted ${sortedMessages.length} error messages.`);
  });
});
